#!/bin/sh

set -e

# cd python
# if [[ $TRAVIS_OS_NAME == 'osx' ]];
# then
#   python setup.py install
# else
#   python setup.py install --user
# fi
# cd ..
# python -c 'from spidriver import SPIDriver' 

# cd c
# make -f linux/Makefile
